(()=>{"use strict";
const $=s=>document.querySelector(s),canvas=$("#game"),ctx=canvas.getContext("2d"),stage=$("#stage"),reduceMotion=matchMedia("(prefers-reduced-motion: reduce)").matches;
const G=.82,LY=.13;
const defs=[
{name:"first mark",sol:.22,targets:[.70],heights:[.26],tol:.036,hint:"One figure. Watch how the shadow moves opposite the lamp."},
{name:"cross-light",sol:.78,targets:[.25,.62],heights:[.22,.34],tol:.030,hint:"Two marks must agree on one lamp position."},
{name:"three actors",sol:.30,targets:[.18,.50,.79],heights:[.18,.30,.24],tol:.026,hint:"Different heights make the tips travel at different rates."},
{name:"low rail",sol:.66,targets:[.16,.46,.83],heights:[.31,.20,.36],tol:.022,hint:"The tall figures amplify tiny lamp movements."},
{name:"near wing",sol:.18,targets:[.40,.64,.86],heights:[.28,.16,.32],tol:.020,hint:"The useful lamp position is close to the left end of the rail."},
{name:"company",sol:.82,targets:[.14,.38,.61,.82],heights:[.20,.35,.25,.18],tol:.018,hint:"Four shadows, one answer. Move slowly near a good fit."},
{name:"split bill",sol:.34,targets:[.12,.36,.62,.86],heights:[.24,.19,.33,.27],tol:.016,hint:"The floor marks are narrower now."},
{name:"last rehearsal",sol:.68,targets:[.10,.32,.58,.84],heights:[.34,.22,.29,.17],tol:.014,hint:"Tall and short figures disagree quickly when the lamp drifts."},
{name:"full house",sol:.48,targets:[.08,.28,.52,.73,.90],heights:[.21,.33,.18,.30,.24],tol:.012,hint:"Five tips. The center of the rail is less forgiving than it looks."}
];
function makeLevel(d){return {...d,posts:d.targets.map((t,i)=>{const h=d.heights[i],top=G-h,q=(G-LY)/(top-LY);return d.sol+(t-d.sol)/q})}}
const LEVELS=defs.map(makeLevel),colors=["#d8a74a","#c95b43","#8ca35e","#6f9da2","#c17a3c"];
let W=0,H=0,dpr=1,level=0,L=LEVELS[0],lamp=.5,drag=false,sweeps=0,lockStart=0,raf=0,won=false,unlocked=1,bests={},soundOn=true,audio=null;
function load(){try{unlocked=Math.max(1,Math.min(LEVELS.length,Number(localStorage.getItem("longShadowUnlocked")||1)));bests=JSON.parse(localStorage.getItem("longShadowBests")||"{}");soundOn=localStorage.getItem("longShadowSound")!=="off"}catch(e){}}
function save(k,v){try{localStorage.setItem(k,v)}catch(e){}}
function tone(freq,d=.08,type="sine",gain=.035){if(!soundOn)return;try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch(e){}}
function buzz(v){navigator.vibrate?.(v)}
function fit(){const r=stage.getBoundingClientRect();W=r.width;H=r.height;dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);canvas.style.width=W+"px";canvas.style.height=H+"px";ctx.setTransform(dpr,0,0,dpr,0,0);draw()}
function sx(x){return x*W}function sy(y){return y*H}
function tipX(lx,px,h){const top=G-h,q=(G-LY)/(top-LY);return lx+q*(px-lx)}
function errorAt(lx){let worst=0;for(let i=0;i<L.posts.length;i++)worst=Math.max(worst,Math.abs(tipX(lx,L.posts[i],L.heights[i])-L.targets[i])/L.tol);return worst}
function aligned(){return errorAt(lamp)<=1}
function setLampFromClient(x){const r=canvas.getBoundingClientRect();lamp=Math.max(.07,Math.min(.93,(x-r.left)/r.width));lockStart=0;$("#lock").classList.remove("on");draw()}
function begin(e){if(won)return;e.preventDefault();drag=true;sweeps++;$("#sweeps").textContent=sweeps;setLampFromClient(e.clientX);canvas.setPointerCapture?.(e.pointerId);tone(150,.025,"triangle",.012)}
function move(e){if(!drag||won)return;e.preventDefault();setLampFromClient(e.clientX)}
function end(){drag=false}
function reset(i=level){cancelAnimationFrame(raf);level=i;L=LEVELS[i];lamp=.5;drag=false;sweeps=0;lockStart=0;won=false;$("#roomNo").textContent=String(i+1).padStart(2,"0");$("#roomName").textContent=L.name;$("#sweeps").textContent="0";$("#best").textContent=bests[i]??"—";$("#instruction").textContent=L.hint;$("#win").classList.add("hidden");$("#lock").classList.remove("on");draw();raf=requestAnimationFrame(loop)}
function loop(t){if(!won){if(aligned()){if(!lockStart){lockStart=t;$("#lock").classList.add("on")}const p=Math.min(1,(t-lockStart)/520);$("#lock span").style.width=(p*100)+"%";if(p>=1){finish();return}}else{lockStart=0;$("#lock").classList.remove("on");$("#lock span").style.width="0%"}draw();raf=requestAnimationFrame(loop)}}
function finish(){won=true;cancelAnimationFrame(raf);const score=Math.max(1,sweeps);if(bests[level]==null||score<bests[level]){bests[level]=score;save("longShadowBests",JSON.stringify(bests));$("#best").textContent=score}if(level===unlocked-1&&unlocked<LEVELS.length){unlocked++;save("longShadowUnlocked",String(unlocked));renderPicker()}tone(294,.08,"sine",.04);setTimeout(()=>tone(440,.1,"sine",.035),80);setTimeout(()=>tone(588,.14,"sine",.03),160);buzz([12,25,18]);$("#winKicker").textContent=level===LEVELS.length-1?"HOUSE DARK":"ROOM HELD";$("#winTitle").textContent=L.name;$("#winText").textContent=`${score} sweep${score===1?"":"s"}. ${level<LEVELS.length-1?"The next room is unlocked.":"All nine rooms are complete."}`;$("#next").textContent=level<LEVELS.length-1?"next room":"rooms";$("#win").classList.remove("hidden");draw()}
function draw(){ctx.clearRect(0,0,W,H);const floorY=sy(G),railY=sy(LY),lampX=sx(lamp);const grad=ctx.createLinearGradient(0,0,0,H);grad.addColorStop(0,"#5a2825");grad.addColorStop(.58,"#341a19");grad.addColorStop(1,"#17100f");ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);ctx.fillStyle="#1b1211";ctx.fillRect(0,floorY,W,H-floorY);ctx.strokeStyle="#8a6d46";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,floorY);ctx.lineTo(W,floorY);ctx.stroke();ctx.strokeStyle="#d3a54e";ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(sx(.06),railY);ctx.lineTo(sx(.94),railY);ctx.stroke();for(let x=.08;x<.94;x+=.06){ctx.strokeStyle="rgba(231,216,180,.35)";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(sx(x),railY-5);ctx.lineTo(sx(x),railY+5);ctx.stroke()}ctx.save();ctx.globalAlpha=.13;ctx.fillStyle="#f2c96b";ctx.beginPath();ctx.moveTo(lampX,railY+8);ctx.lineTo(sx(.02),floorY);ctx.lineTo(sx(.98),floorY);ctx.closePath();ctx.fill();ctx.restore();for(let i=0;i<L.targets.length;i++){const t=L.targets[i],tol=L.tol,c=colors[i%colors.length],ok=Math.abs(tipX(lamp,L.posts[i],L.heights[i])-t)<=tol;ctx.fillStyle=ok?"#9fb66d":c;ctx.fillRect(sx(t-tol),floorY+6,sx(tol*2),9);ctx.strokeStyle="#16100f";ctx.lineWidth=1;ctx.strokeRect(sx(t-tol),floorY+6,sx(tol*2),9);ctx.fillStyle="#e8d9b6";ctx.font=`700 ${Math.max(9,Math.min(12,W/36))}px Courier New`;ctx.textAlign="center";ctx.fillText(String(i+1),sx(t),floorY+31)}for(let i=0;i<L.posts.length;i++){const px=L.posts[i],h=L.heights[i],tx=tipX(lamp,px,h),c=colors[i%colors.length];ctx.save();ctx.globalAlpha=.72;ctx.fillStyle="#090707";ctx.beginPath();ctx.moveTo(sx(px)-4,floorY);ctx.lineTo(sx(px)+4,floorY);ctx.lineTo(sx(tx),floorY+2);ctx.closePath();ctx.fill();ctx.restore();ctx.fillStyle=c;ctx.fillRect(sx(px)-5,sy(G-h),10,sy(h));ctx.fillStyle="#17100f";ctx.beginPath();ctx.arc(sx(px),sy(G-h)-6,6,0,Math.PI*2);ctx.fill();ctx.strokeStyle=c;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(sx(px),sy(G-h)+8);ctx.lineTo(sx(px),floorY);ctx.stroke();ctx.fillStyle="#e8d9b6";ctx.font="700 9px Courier New";ctx.textAlign="center";ctx.fillText(String(i+1),sx(px),sy(G-h)-16)}ctx.fillStyle="#d8a74a";ctx.beginPath();ctx.arc(lampX,railY,12,0,Math.PI*2);ctx.fill();ctx.fillStyle="#17100f";ctx.beginPath();ctx.moveTo(lampX-10,railY+2);ctx.lineTo(lampX+10,railY+2);ctx.lineTo(lampX+6,railY+12);ctx.lineTo(lampX-6,railY+12);ctx.closePath();ctx.fill();ctx.fillStyle="#f2c96b";ctx.beginPath();ctx.arc(lampX,railY+9,4,0,Math.PI*2);ctx.fill();if(!won){const e=errorAt(lamp);ctx.fillStyle=e<=1?"#9fb66d":"rgba(231,216,180,.62)";ctx.font="700 9px Courier New";ctx.textAlign="left";ctx.fillText(e<=1?"HOLD":"MOVE LAMP",10,H-42)}}
function renderPicker(){const box=$("#roomList");box.innerHTML=LEVELS.map((r,i)=>`<button data-i="${i}" ${i>=unlocked?"disabled":""}><strong>${String(i+1).padStart(2,"0")}</strong><span>${r.name}${bests[i]!=null?` · best ${bests[i]}`:""}</span></button>`).join("");box.querySelectorAll("button:not([disabled])").forEach(b=>b.onclick=()=>{reset(Number(b.dataset.i));$("#picker").classList.add("hidden")})}
canvas.addEventListener("pointerdown",begin);canvas.addEventListener("pointermove",move);canvas.addEventListener("pointerup",end);canvas.addEventListener("pointercancel",end);$("#reset").onclick=()=>reset(level);$("#rooms").onclick=()=>{$("#picker").classList.remove("hidden");renderPicker()};$("#close").onclick=()=>$("#picker").classList.add("hidden");$("#start").onclick=()=>{$("#intro").classList.add("hidden");reset(0);tone(220,.06)};$("#again").onclick=()=>reset(level);$("#next").onclick=()=>{if(level<LEVELS.length-1)reset(level+1);else{$("#win").classList.add("hidden");$("#picker").classList.remove("hidden");renderPicker()}};$("#sound").onclick=()=>{soundOn=!soundOn;save("longShadowSound",soundOn?"on":"off");$("#sound").textContent=soundOn?"sound on":"sound off";if(soundOn)tone(220,.05)};window.addEventListener("resize",fit);window.addEventListener("keydown",e=>{if($("#intro").classList.contains("hidden")===false)return;if(e.key==="ArrowLeft"||e.key==="ArrowRight"){e.preventDefault();if(!won){lamp=Math.max(.07,Math.min(.93,lamp+(e.key==="ArrowLeft"?-.006:.006)));draw()}}if(e.key==="r"||e.key==="R")reset(level);if(e.key==="Enter"&&won)$("#next").click();if(e.key==="Escape")$("#picker").classList.add("hidden")});load();$("#sound").textContent=soundOn?"sound on":"sound off";renderPicker();fit();
})();
